USE EXPENDIO
GO

CREATE VIEW VW_PRODUCTO AS
SELECT P.PDT_CODIGO AS CODIGO, P.PDT_DESCRIPCION AS ARTICULO, C.CAT_DESCRIPCION AS CATEGORIA, 
P.PDT_PRECIO AS PRECIO, P.PDT_INVENTARIO AS INVENTARIO
FROM PRODUCTO AS P INNER JOIN CATEGORIA AS C 
ON P.PDT_ID_CATEGORIA = C.CAT_ID

GO