
--============SP_PRODUCTO========================

CREATE PROCEDURE SP_PRODUCTO
@OP INT = 0,
@ID INT = 0,
@CODIGO VARCHAR(50) = '',
@ID_CAT INT = 0,
@DESCRIPCION VARCHAR(50)= '',
@PRECIO FLOAT = 0,
@INVENTARIO INT = 0
AS
BEGIN

	IF @OP = 1
	BEGIN
		SELECT * FROM VW_PRODUCTO
	END
	IF @OP = 2
	BEGIN
		IF NOT EXISTS(SELECT 1 FROM VW_PRODUCTO WHERE CODIGO = @CODIGO)
		BEGIN
			INSERT INTO PRODUCTO VALUES(
			(SELECT ISNULL(MAX(PDT_ID), 0) + 1 FROM PRODUCTO),
			@CODIGO, @ID_CAT, @DESCRIPCION, @PRECIO, @INVENTARIO)
		END
		ELSE
		BEGIN
			UPDATE PRODUCTO SET
			PDT_ID_CATEGORIA = @ID_CAT,
			PDT_DESCRIPCION = @DESCRIPCION,
			PDT_PRECIO = @PRECIO,
			PDT_INVENTARIO = @INVENTARIO
			WHERE PDT_CODIGO = @CODIGO
		END
	END
	IF @OP = 3
	BEGIN
		DELETE FROM PRODUCTO WHERE PDT_CODIGO = @CODIGO
	END

END

GO